on:
  push:
     branches:
       - master

  

name: renderbook

jobs:
  bookdown:
    name: Render-Book
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install rg and jags
        run: |
          brew update 
          brew install ripgrep
          brew install jags
      - name: Install port
        run: |
          wget https://github.com/macports/macports-base/releases/download/v2.8.0/MacPorts-2.8.0-12-Monterey.pkg
          sudo installer -pkg ./MacPorts-2.8.0-12-Monterey.pkg -target /
      - name: Install latex
        run: |
          sudo /opt/local/bin/port install texlive-latex
          sudo /opt/local/bin/port install texlive-latex-extra
          sudo /opt/local/bin/port install texlive-luatex
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install dependencies
        run: ./scripts/install_dependencies.sh
        shell: bash
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown"))'
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      - name: Render Book
        run: |
          Rscript -e 'bookdown::render_book("index.Rmd")'
          Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::pdf_book")'
      - uses: actions/upload-artifact@v1
        with:
          name: _book
          path: _book/
  
  checkout-and-deploy:
    runs-on: ubuntu-latest
    needs: bookdown
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          # Artifact name
          name: _book # optional
          # Destination path
          path: _book # optional
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }} # https://github.com/settings/tokens
          EMAIL: ${{ secrets.EMAIL }}               # must be a verified email
          BUILD_DIR: _book/
        with:
          email: zampinetti@gmail.com
          build_dir: _book/                    # "_site/" by default

    
 
